apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: deployment-sa
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key
              key: API_KEY
        volumeMounts:
        - name: api-key-volume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: api-key-volume
        secret:
          secretName: api-key
